pipeline {
    agent any
    stages {
        stage("Clean up") {
            steps {
                deleteDir()
            }
        }
        stage('Build') {
            steps {
                sh 'mvn -B -DskipTests clean package'
            }
        }
        stage('Test') {
            steps {
                dir("simple-java-maven-app"){
                    sh 'mvn test'
                }
            }
        }
        stage('Deliver') {
            steps {
                dir("simple-java-maven-app") {
                    sh './jenkins/scripts/deliver.sh'
                }
            }
        }
        stage('Complete'){
            steps {
                echo "Build complete"
            }
        }
    }
}
